/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject1;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class class4 extends javax.swing.JFrame {

    /**
     * Creates new form class4
     */
    int[][] adc=new int[25][61];
    int[][] adg=new int[25][61];
    int[][] Ic=new int[25][61];
    int[][] Ig=new int[25][61];
    int[][] IIc=new int[25][61];
    int[][] IIg=new int[25][61];
    int[][] IIIc=new int[25][61];
    int[][] IIIg=new int[25][61];
    
    
    int[][] a1=new int[25][61];
    int[][] a2=new int[25][61];
    
    float[] enh = new float[100000];
    float[] enm = new float[100000];
    float[] exh = new float[100000];
    float[] exm = new float[100000];
    
    int cnt=0,tot=0,flag=1;
    String bName;
    int[] lim=new int[10];
    
    public class4() {
        initComponents();
    }


    // class 3 se aaya hai
    class4(String bName1, float[] enh1, float[] enm1, float[] exh1, float[] exm1, int cnt1, int tot1, int[][] ad1, int[][] ad2, int[][] I1, int[][] I2, int[][] II1, int[][] II2, int[][] III1, int[][] III2,int[] lim1) {
        
        bName=bName1;
        cnt=cnt1;
        tot=tot1;
        
        System.out.println("------" + bName);
        
        for(int i=0;i<cnt;++i)
        {
            int x=(int)enh1[i];
            int y=(int)enm1[i];
            
            System.out.println(x + " " + y);
            if(bName.equals("Auditorium")) adc[x][y]++;
            if(bName.equals("CC-I")) Ic[x][y]++;
            if(bName.equals("CCtwo")) IIc[x][y]++;
            if(bName.equals("CC-III")) IIIc[x][y]++;
            
            a1[x][y]++;
            
            x=(int)exh1[i];
            y=(int)exm1[i];
            
            System.out.println(x + " " + y);
            if(bName.equals("Auditorium")) adg[x][y]++;
            if(bName.equals("CC-I")) Ig[x][y]++;
            if(bName.equals("CCtwo")) IIg[x][y]++;
            if(bName.equals("CC-III")) IIIg[x][y]++;
            
            a2[x][y]++;
            
            System.out.println("-.-.-.-");
        }
        
        for(int i=0;i<24;++i)
        {
            for(int j=0;j<60;++j)
            {
                adc[i][j]+=ad1[i][j];
                adg[i][j]+=ad2[i][j];
                Ic[i][j]+=I1[i][j];
                Ig[i][j]+=I2[i][j];
                IIc[i][j]+=II1[i][j];
                IIg[i][j]+=II2[i][j];
                IIIc[i][j]+=III1[i][j];
                IIIg[i][j]+=III2[i][j];
            }
        }
        
        for(int i=1;i<10;++i) lim[i]=lim1[i];
        
        
        
//        for(int i=0;i<24;++i)
//        {
//            for(int j=0;j<60;++j)
//            {
//                if(a1[i][j]!=0)
//                System.out.println(a1[i][j] + " " + IIc[i][j]);
//            }
//        }
        
        initComponents();
    }

    // classMain se aaya hai !!
    class4(int[][] ad1, int[][] ad2, int[][] I1, int[][] I2, int[][] II1, int[][] II2, int[][] III1, int[][] III2, int[] lim1) {
        
        for(int i=0;i<24;++i)
        {
            for(int j=0;j<60;++j)
            {
                adc[i][j]+=ad1[i][j];
                adg[i][j]+=ad2[i][j];
                Ic[i][j]+=I1[i][j];
                Ig[i][j]+=I2[i][j];
                IIc[i][j]+=II1[i][j];
                IIg[i][j]+=II2[i][j];
                IIIc[i][j]+=III1[i][j];
                IIIg[i][j]+=III2[i][j];
            }
        }
        
        for(int i=1;i<10;++i) lim[i]=lim1[i];
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        in = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        out = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Report");

        jButton5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton5.setText("Quit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton6.setText("Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        in.setEditable(false);
        in.setColumns(20);
        in.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        in.setRows(5);
        jScrollPane1.setViewportView(in);

        out.setEditable(false);
        out.setColumns(20);
        out.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        out.setRows(5);
        jScrollPane2.setViewportView(out);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Check-in time Users");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Check-out time Users");

        jButton1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jComboBox1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auditorium", "CC-I", "CCtwo", "CC-III" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jButton3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton3.setText("Show");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jButton6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))))))
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel2)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel3)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
            System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
        
        classMain h=new classMain(adc,adg,Ic,Ig,IIc,IIg,IIIc,IIIg,lim);
        h.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
//        if(bName.equals("Auditorium")) lim[1]+=cnt;
//        if(bName.equals("CC-I")) lim[3]+=cnt;
//        if(bName.equals("CCtwo")) lim[5]+=cnt;
//        if(bName.equals("CC-III")) lim[7]+=cnt;
        System.out.println("Yes");
        
        if(flag==1)
        {
            flag=0;
            for(int i=0;i<=23;++i)
            {
                for(int j=0;j<=59;++j)
                {
                    if(bName.equals("Auditorium"))
                    {
                        jLabel4.setText("Auditorium");
                        jLabel5.setText("Current Status: " + lim[1] + "/" + lim[2]);
                        
                        if(adc[i][j]!=0)
                        {
                            flag++;
                            if(j<10)
                                in.append("Time-" + i + ":0" + j + ", " + "Users : " + adc[i][j] + "\n");
                            else
                                in.append("Time-" + i + ":" + j + ", " + "Users : " + adc[i][j] + "\n");
                        }

                        if(adg[i][j]!=0)
                        {
                            flag++;
                            if(j<10)
                                out.append("Time-" + i + ":0" + j + ", " + "Users : " + adg[i][j] + "\n");
                            else
                                out.append("Time-" + i + ":" + j + ", " + "Users : " + adg[i][j] + "\n");
                        }
                    }
                    if(bName.equals("CC-I"))
                    {
                        jLabel4.setText("CC-I");
                        jLabel5.setText("Current Status: " + lim[3] + "/" + lim[4]);
                        
                        if(Ic[i][j]!=0)
                        {
                            flag++;
                            if(j<10)
                                in.append("Time-" + i + ":0" + j + ", " + "Users : " + Ic[i][j] + "\n");
                            else
                                in.append("Time-" + i + ":" + j + ", " + "Users : " + Ic[i][j] + "\n");
                        }

                        if(Ig[i][j]!=0)
                        {
                            flag++;
                            if(j<10)
                                out.append("Time-" + i + ":0" + j + ", " + "Users : " + Ig[i][j] + "\n");
                            else
                                out.append("Time-" + i + ":" + j + ", " + "Users : " + Ig[i][j] + "\n");
                        }
                    }
                    if(bName.equals("CCtwo"))
                    {
                        jLabel4.setText("CC-II");
                        jLabel5.setText("Current Status: " + lim[5] + "/" + lim[6]);
                        
                        if(IIc[i][j]!=0)
                        {
                            flag++;
                            if(j<10)
                                in.append("Time-" + i + ":0" + j + ", " + "Users : " + IIc[i][j] + "\n");
                            else
                                in.append("Time-" + i + ":" + j + ", " + "Users : " + IIc[i][j] + "\n");
                        }

                        if(IIg[i][j]!=0)
                        {
                            flag++;
                            if(j<10)
                                out.append("Time-" + i + ":0" + j + ", " + "Users : " + IIg[i][j] + "\n");
                            else
                                out.append("Time-" + i + ":" + j + ", " + "Users : " + IIg[i][j] + "\n");
                        }
                    }
                    if(bName.equals("CC-III"))
                    {
                        jLabel4.setText("CC-III");
                        jLabel5.setText("Current Status: " + lim[7] + "/" + lim[8]);
                        
                        if(IIIc[i][j]!=0)
                        {
                            flag++;
                            if(j<10)
                                in.append("Time-" + i + ":0" + j + ", " + "Users : " + IIIc[i][j] + "\n");
                            else
                                in.append("Time-" + i + ":" + j + ", " + "Users : " + IIIc[i][j] + "\n");
                        }

                        if(IIIg[i][j]!=0)
                        {
                            flag++;
                            if(j<10)
                                out.append("Time-" + i + ":0" + j + ", " + "Users : " + IIIg[i][j] + "\n");
                            else
                                out.append("Time-" + i + ":" + j + ", " + "Users : " + IIIg[i][j] + "\n");
                        }
                    }
                }
            }
            System.out.println("flag : " + flag);
            if(flag==0)
            {
                in.append("There is no any user...");
                out.append("There is no any user...");
            }
            JOptionPane.showMessageDialog(null,"Data Saved.");
        }
        flag=0;
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String[] items = {"Auditorium", "CC-I", "CCtwo", "CC-III"};
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jComboBox1.getSelectedItem().toString());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        bName=jTextField1.getText();
        
        in.setText("");
        out.setText("");
        
        int x=0;
        
        for(int i=0;i<=23;++i)
            {
                for(int j=0;j<=59;++j)
                {
                    if(bName.equals("Auditorium"))
                    {
                        jLabel4.setText("Auditorium");
                        jLabel5.setText("Current Status: " + lim[1] + "/" + lim[2]);
                        
                        if(adc[i][j]!=0)
                        {
                            x++;
                            if(j<10)
                                in.append("Time-" + i + ":0" + j + ", " + "Users : " + adc[i][j] + "\n");
                            else
                                in.append("Time-" + i + ":" + j + ", " + "Users : " + adc[i][j] + "\n");
                        }

                        if(adg[i][j]!=0)
                        {
                            x++;
                            if(j<10)
                                out.append("Time-" + i + ":0" + j + ", " + "Users : " + adg[i][j] + "\n");
                            else
                                out.append("Time-" + i + ":" + j + ", " + "Users : " + adg[i][j] + "\n");
                        }
                    }
                    if(bName.equals("CC-I"))
                    {
                        jLabel4.setText("CC-I");    jLabel5.setText("Current Status: " + lim[3] + "/" + lim[4]);
                        if(Ic[i][j]!=0)
                        {
                            x++;
                            if(j<10)
                                in.append("Time-" + i + ":0" + j + ", " + "Users : " + Ic[i][j] + "\n");
                            else
                                in.append("Time-" + i + ":" + j + ", " + "Users : " + Ic[i][j] + "\n");
                        }

                        if(Ig[i][j]!=0)
                        {
                            x++;
                            if(j<10)
                                out.append("Time-" + i + ":0" + j + ", " + "Users : " + Ig[i][j] + "\n");
                            else
                                out.append("Time-" + i + ":" + j + ", " + "Users : " + Ig[i][j] + "\n");
                        }
                    }
                    if(bName.equals("CCtwo"))
                    {
                        jLabel4.setText("CC-II");   jLabel5.setText("Current Status: " + lim[5] + "/" + lim[6]);
                        if(IIc[i][j]!=0)
                        {
                            x++;
                            if(j<10)
                                in.append("Time-" + i + ":0" + j + ", " + "Users : " + IIc[i][j] + "\n");
                            else
                                in.append("Time-" + i + ":" + j + ", " + "Users : " + IIc[i][j] + "\n");
                        }

                        if(IIg[i][j]!=0)
                        {
                            x++;
                            if(j<10)
                                out.append("Time-" + i + ":0" + j + ", " + "Users : " + IIg[i][j] + "\n");
                            else
                                out.append("Time-" + i + ":" + j + ", " + "Users : " + IIg[i][j] + "\n");
                        }
                    }
                    if(bName.equals("CC-III"))
                    {
                        jLabel4.setText("CC-III");  jLabel5.setText("Current Status: " + lim[7] + "/" + lim[8]);
                        if(IIIc[i][j]!=0)
                        {
                            x++;
                            if(j<10)
                                in.append("Time-" + i + ":0" + j + ", " + "Users : " + IIIc[i][j] + "\n");
                            else
                                in.append("Time-" + i + ":" + j + ", " + "Users : " + IIIc[i][j] + "\n");
                        }

                        if(IIIg[i][j]!=0)
                        {
                            x++;
                            if(j<10)
                                out.append("Time-" + i + ":0" + j + ", " + "Users : " + IIIg[i][j] + "\n");
                            else
                                out.append("Time-" + i + ":" + j + ", " + "Users : " + IIIg[i][j] + "\n");
                        }
                    }
                }
            }
            
            if(x==0)
            {
                in.append("There is no any user...");
                out.append("There is no any user...");
            }
            JOptionPane.showMessageDialog(null,"Data Saved.");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(class4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(class4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(class4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(class4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new class4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea in;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea out;
    // End of variables declaration//GEN-END:variables
}
