/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject1;

import static java.lang.Math.abs;
import java.util.ArrayList;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class class1 extends javax.swing.JFrame {

    /**
     * Creates new form class1
     */
    int [] lim=new int[10];
    
    int[][] adc=new int[25][61];
    int[][] adg=new int[25][61];
    int[][] Ic=new int[25][61];
    int[][] Ig=new int[25][61];
    int[][] IIc=new int[25][61];
    int[][] IIg=new int[25][61];
    int[][] IIIc=new int[25][61];
    int[][] IIIg=new int[25][61];
    
    
    float[] enh = new float[100000];
    float[] enm = new float[100000];
    float[] exh = new float[100000];
    float[] exm = new float[100000];
    
    
    public class1()
    {
        initComponents();
    }
    
    int tot=0,cnt=0,num=0;
    String bName;
    
    
    
    //classMian se aaya hai
    class1(int tot1, String bName1, int cnt1, int[][] ad1, int[][] ad2, int[][] I1, int[][] I2, int[][] II1, int[][] II2, int[][] III1, int[][] III2,int[] lim1) {
        
        tot=tot1;
        bName=bName1;
        cnt=cnt1;
        
        for(int i=0;i<24;++i)
        {
            for(int j=0;j<60;++j)
            {
                adc[i][j]=ad1[i][j];
                adg[i][j]=ad2[i][j];
                Ic[i][j]=I1[i][j];
                Ig[i][j]=I2[i][j];
                IIc[i][j]=II1[i][j];
                IIg[i][j]=II2[i][j];
                IIIc[i][j]=III1[i][j];
                IIIg[i][j]=III2[i][j];
            }
        }
        for(int i=1;i<10;++i) lim[i]=lim1[i];
        
        initComponents();
    }

    // class 3 se aaya hai
    class1(String bName1, int tot1, int cnt1, float[] enh1, float[] enm1, float[] exh1, float[] exm1, int[][] ad1, int[][] ad2, int[][] I1, int[][] I2, int[][] II1, int[][] II2, int[][] III1, int[][] III2,int[] lim1) {
        
        tot=tot1;
        cnt+=cnt1;
        bName=bName1;
        
        for(int i=0;i<cnt;++i)
        {
            enh[i]=enh1[i];
            enm[i]=enm1[i];
            exh[i]=exh1[i];
            exm[i]=exm1[i];
        }
        
        for(int i=0;i<24;++i)
        {
            for(int j=0;j<60;++j)
            {
                adc[i][j]=ad1[i][j];
                adg[i][j]=ad2[i][j];
                Ic[i][j]=I1[i][j];
                Ig[i][j]=I2[i][j];
                IIc[i][j]=II1[i][j];
                IIg[i][j]=II2[i][j];
                IIIc[i][j]=III1[i][j];
                IIIg[i][j]=III2[i][j];
            }
        }
        for(int i=1;i<10;++i) lim[i]=lim1[i];
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        n = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        n.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Availability Checking");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Enter No. of new users :");

        jButton2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
       
//        num=Integer.parseInt(n.getText());
        
    }//GEN-LAST:event_nActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String s1=n.getText();
//        int flag=0,sz=s1.length();
        
        try {
            Integer.parseInt(s1);
            System.out.println("Integer hai");
            
            num=Integer.parseInt(n.getText());
            num=abs(num);
            
            System.out.println(num + " " + tot);
            
            if(bName.equals("Auditorium"))
            {
                if(num>(lim[2]-lim[1])){
                    JOptionPane.showMessageDialog(null,"Error, No more seats are avilable.");
                    num=0;
                }
                else {
                    JOptionPane.showMessageDialog(null,"Data Saved.");
                }
            }
            if(bName.equals("CC-I"))
            {
                if(num>(lim[4]-lim[3])){
                    JOptionPane.showMessageDialog(null,"Error, No more seats are avilable.");
                    num=0;
                }
                else {
                    JOptionPane.showMessageDialog(null,"Data Saved.");
                }
            }
            if(bName.equals("CCtwo"))
            {
                if(num>(lim[6]-lim[5])){
                    JOptionPane.showMessageDialog(null,"Error, No more seats are avilable.");
                    num=0;
                }
                else {
                    JOptionPane.showMessageDialog(null,"Data Saved.");
                }
            }
            if(bName.equals("CC-III"))
            {
                if(num>(lim[8]-lim[7])){
                    JOptionPane.showMessageDialog(null,"Error, No more seats are avilable.");
                    num=0;
                }
                else {
                    JOptionPane.showMessageDialog(null,"Data Saved.");
                }
            }
            
        }
        catch (NumberFormatException e) {
            System.out.println("Integer nhi hai");
            
            jLabel3.setText("Invalid Input !!!");
            n.setText("");
        }
        
        
        
//        num=ThreadLocalRandom.current().nextInt(1,tot);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        if(num>=0)

        dispose();

        class3 cc3=new class3(tot,num,bName,cnt,enh,enm,exh,exm,adc,adg,Ic,Ig,IIc,IIg,IIIc,IIIg,lim);
        cc3.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(class1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(class1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(class1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(class1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new class1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField n;
    // End of variables declaration//GEN-END:variables
}
